/**
 * Engine Schema — re-exports from @ditto/core
 *
 * The engine schema is owned by packages/core/src/db/schema.ts.
 * This file is a thin re-export following the engine-first pattern:
 * "change packages/core/ first, src/engine/ files are thin re-exports."
 *
 * Tables: processes, processDependencies, agents, processRuns, stepRuns,
 * processOutputs, harnessDecisions, trustChanges, trustSuggestions,
 * feedback, memories, improvements, workItems, activities, credentials,
 * outboundActions, schedules, delayedRuns, workspaceViews, processVersions,
 * bridgeDevices, bridgePairingCodes, bridgeJobs (Brief 212),
 * projects, projectRunners, runnerDispatches (Brief 215)
 */

export {
  // Type unions
  processStatusValues,
  type ProcessStatus,
  trustTierValues,
  type TrustTier,
  runStatusValues,
  type RunStatus,
  stepExecutorValues,
  type StepExecutor,
  feedbackTypeValues,
  type FeedbackType,
  editSeverityValues,
  type EditSeverity,
  trustChangeActorValues,
  type TrustChangeActor,
  trustSuggestionStatusValues,
  type TrustSuggestionStatus,
  agentStatusValues,
  type AgentStatus,
  agentCategoryValues,
  type AgentCategory,
  improvementStatusValues,
  type ImprovementStatus,
  trustActionValues,
  type TrustAction,
  reviewResultValues,
  type ReviewResult,
  memoryScopeTypeValues,
  type MemoryScopeType,
  memoryTypeValues,
  type MemoryType,
  memorySourceValues,
  type MemorySource,
  workItemTypeValues,
  type WorkItemType,
  workItemStatusValues,
  type WorkItemStatus,
  workItemSourceValues,
  type WorkItemSource,
  briefStateValues,
  type BriefState,
  delayedRunStatusValues,
  type DelayedRunStatus,
  bridgeDeviceStatusValues,
  type BridgeDeviceStatus,
  bridgeJobStateColumnValues,
  type BridgeJobStateColumn,
  bridgeJobKindColumnValues,
  type BridgeJobKindColumn,
  bridgeJobRoutedAsValues,
  type BridgeJobRoutedAs,
  // Brief 215 — Projects + Runner Registry
  runnerKindValues,
  type RunnerKindValue,
  runnerModeValues,
  type RunnerModeValue,
  runnerModeRequiredValues,
  type RunnerModeRequiredValue,
  runnerDispatchStatusValues,
  type RunnerDispatchStatusValue,
  runnerHealthStatusValues,
  type RunnerHealthStatusValue,
  harnessTypeValues,
  type HarnessTypeValue,
  briefSourceValues,
  type BriefSourceValue,
  deployTargetValues,
  type DeployTargetValue,
  projectStatusValues,
  type ProjectStatusValue,

  // Tables
  processes,
  processDependencies,
  agents,
  processRuns,
  stepRuns,
  processOutputs,
  harnessDecisions,
  trustChanges,
  trustSuggestions,
  feedback,
  memories,
  improvements,
  workItems,
  activities,
  credentials,
  outboundActions,
  schedules,
  delayedRuns,
  workspaceViews,
  processVersions,
  bridgeDevices,
  bridgePairingCodes,
  bridgeJobs,
  projects,
  projectRunners,
  runnerDispatches,
} from "@ditto/core";
