"use client";

import { useState } from "react";
import { ArrowRight } from "lucide-react";
import { ChatMessage } from "./chat-message";

/**
 * Post-submission engagement phase.
 * Alex asks a contextual follow-up question (generated by LLM) to enrich intake,
 * then shows "What happens next" timeline.
 *
 * If no follow-up question is provided (LLM unavailable or conversation was
 * already rich enough), skips straight to the timeline.
 *
 * Provenance: Formless.ai enrichment pattern, Brief 094.
 */

type Phase = "ask" | "answered" | "skipped";

export function PostSubmission({
  sessionId,
  surface,
  followUpQuestion,
}: {
  sessionId: string;
  surface: string;
  followUpQuestion?: string;
}) {
  // Skip the question phase if no follow-up was generated
  const [phase, setPhase] = useState<Phase>(followUpQuestion ? "ask" : "skipped");
  const [answer, setAnswer] = useState("");
  const [alexReply, setAlexReply] = useState("");
  const [submitting, setSubmitting] = useState(false);

  async function handleAnswer() {
    if (!answer.trim()) return;
    setSubmitting(true);

    try {
      // Record the follow-up answer
      await fetch("/api/v1/network/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: answer.trim(),
          sessionId,
          context: surface,
        }),
      });
      setAlexReply(
        "That\u2019s useful \u2014 I\u2019ll factor that into my first email. Talk soon.",
      );
    } catch {
      setAlexReply("Got it. Talk soon.");
    }

    setPhase("answered");
    setSubmitting(false);
  }

  async function handleSkip() {
    setPhase("skipped");
    // Record skip event
    try {
      await fetch("/api/v1/network/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: "[post_submission_skipped]",
          sessionId,
          context: surface,
        }),
      });
    } catch {
      // Non-critical
    }
  }

  return (
    <div className="space-y-5 animate-fade-in">
      {phase === "ask" && followUpQuestion && (
        <>
          <ChatMessage
            role="alex"
            text={followUpQuestion}
            animate
          />
          <div className="space-y-2">
            <div className="flex gap-2">
              <input
                type="text"
                placeholder="Type your answer..."
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleAnswer();
                  }
                }}
                disabled={submitting}
                className="flex-1 rounded-2xl border-2 border-border bg-white px-5 py-3 text-base text-text-primary placeholder:text-text-muted focus:border-vivid focus:outline-none focus:ring-0"
              />
              <button
                type="button"
                onClick={handleAnswer}
                disabled={submitting || !answer.trim()}
                className="inline-flex items-center gap-1 rounded-2xl bg-vivid px-5 py-3 text-base font-semibold text-white transition-colors hover:bg-accent-hover disabled:opacity-60"
              >
                <ArrowRight size={18} />
              </button>
            </div>
            <button
              type="button"
              onClick={handleSkip}
              className="text-sm text-text-muted hover:text-text-secondary"
            >
              Skip — just email me
            </button>
          </div>
        </>
      )}

      {phase === "answered" && (
        <>
          <ChatMessage role="user" text={answer} animate />
          <ChatMessage role="alex" text={alexReply} animate />
        </>
      )}

      {phase === "skipped" && !followUpQuestion && (
        <ChatMessage
          role="alex"
          text="I'll introduce myself properly over email. Talk soon."
          animate
        />
      )}

      {phase === "skipped" && followUpQuestion && (
        <ChatMessage
          role="alex"
          text="No worries. I'll introduce myself properly over email. Talk soon."
          animate
        />
      )}

      {(phase === "answered" || phase === "skipped") && <Timeline />}
    </div>
  );
}

function Timeline() {
  return (
    <div className="mt-6 animate-fade-in rounded-xl border border-border bg-white p-6">
      <p className="mb-4 text-sm font-semibold uppercase tracking-wide text-text-muted">
        What happens next
      </p>
      <div className="space-y-4">
        {[
          "Alex emails you (within the hour)",
          "You reply when you're ready",
          "Alex starts working your network",
        ].map((step, i) => (
          <div key={i} className="flex items-start gap-3">
            <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-vivid-subtle text-xs font-semibold text-vivid">
              {i + 1}
            </div>
            <p className="text-base text-text-secondary">{step}</p>
          </div>
        ))}
      </div>
      <p className="mt-4 text-sm text-text-muted">
        No account needed. No app to download. It all happens in your inbox.
      </p>
    </div>
  );
}
