/**
 * Brief 228 — Retrofit prompt template.
 *
 * Composes the runner-agnostic prompt that gets sent through `dispatchWorkItem`
 * to whichever runner kind the project uses (local-mac-mini, claude-code-routine,
 * claude-managed-agent, github-action). The four runners already exist as
 * adapters via Briefs 212/216/217/218 — this module composes the WORK they do,
 * not the wire they go over.
 *
 * The prompt MUST NOT inline the file contents (token-heavy + diff-noisy per
 * Brief 228 §Constraints). It references the structured `RetrofitDispatchPayload`
 * stored in the workItem `context` by name and instructs the runner to read
 * it from there.
 *
 * Provenance: Original to Ditto (Brief 228); structured-payload-by-reference
 *   pattern is the design call from Brief 228 §Constraints.
 */

import type { RetrofitDispatchPayload } from "@ditto/core";

export interface ComposeRetrofitPromptInput {
  payload: RetrofitDispatchPayload;
  /** Project slug for the user-facing log line on the runner side. */
  projectSlug: string;
  /** Schema version of the `.ditto/` directory shape; written into version.txt. */
  ditoSchemaVersion: number;
}

/** Compose the runner-agnostic prompt + structured payload.
 *  The prompt references `payload` by name; the runner reads its workItem
 *  context to load the actual file contents.
 *
 *  Returns `{ prompt, payloadKey }` so the dispatcher can store the payload
 *  under `payloadKey` in the workItem context. The prompt instructs the
 *  runner to look up `<payloadKey>` in its workItem context. */
export function composeRetrofitPrompt(
  input: ComposeRetrofitPromptInput,
): { prompt: string; payloadKey: string } {
  const { payload, projectSlug, ditoSchemaVersion } = input;
  const payloadKey = "retrofitDispatch";

  const fileSummary = payload.files.length === 0
    ? "(no files to write — re-run produced only `unchanged` files)"
    : payload.files
        .map(
          (f) => `  - ${f.action.padEnd(7)} ${f.path} (${Buffer.byteLength(f.content)} bytes)`,
        )
        .join("\n");

  const prompt = [
    `# Retrofit \`${projectSlug}\`'s \`.ditto/\` substrate (v${ditoSchemaVersion})`,
    "",
    `You are running on behalf of Ditto's project retrofitter (Brief 228).`,
    `Your task is to write a small set of files into the \`.ditto/\` directory at`,
    `the root of the target repo, commit them, and push.`,
    "",
    `## Inputs`,
    "",
    `Read the structured payload from your workItem context under the key`,
    `\`${payloadKey}\` — it carries:`,
    "",
    `- \`commitMessage\`: the exact commit message to use.`,
    `- \`files\`: an array of \`{ path, content, contentHash, action }\` objects.`,
    `- \`branch\`: the default branch to commit + push to.`,
    `- \`processRunId\`: opaque UUID for cross-reference back to Ditto's audit.`,
    "",
    `## Files in this retrofit`,
    "",
    fileSummary,
    "",
    `## Instructions`,
    "",
    `1. Check out \`branch\` from the project's git remote.`,
    `2. For each file in \`files\` (in order):`,
    `   - Create parent directories as needed (e.g. \`.ditto/role-contracts/\`).`,
    `   - Write the file at \`path\` with the exact \`content\` from the payload.`,
    `     Each Ditto-regenerated file is expected to start with a`,
    `     \`# DO NOT EDIT — regenerated by Ditto retrofit (run ${payload.processRunId})\``,
    `     comment on the first line; that header is already in the \`content\` —`,
    `     do NOT add an extra one.`,
    `3. Stage the changes with \`git add .ditto/\`.`,
    `4. Commit with the exact \`commitMessage\` from the payload.`,
    `5. Push to \`branch\`.`,
    `6. POST a structured response in the \`responseBody\` field of your callback to Ditto's status webhook — see "Response shape" below.`,
    "",
    `## Boundaries`,
    "",
    `- Touch ONLY files inside \`.ditto/\`. Never modify sibling directories`,
    `  (\`.git/\`, \`.github/\`, \`.claude/\`, \`.catalyst/\`, etc.) — ADR-043`,
    `  forbids it.`,
    `- If a file's current on-disk content already matches the payload's`,
    `  \`contentHash\` exactly, you may skip writing it (it would be a no-op);`,
    `  list those paths in \`skippedFiles\`.`,
    `- If a file's current on-disk content differs from BOTH the payload`,
    `  AND the prior retrofit's hash, treat it as user-edited and skip it;`,
    `  list it in \`skippedFiles\` with the suffix \` (user-edited)\`.`,
    `- DO NOT \`git push --force\`. If the branch has diverged, abort with a`,
    `  clear error and let Ditto re-run later.`,
    "",
    `## Response shape`,
    "",
    `When you POST your callback to Ditto's status webhook (\`POST /api/v1/work-items/<id>/status\`),`,
    `include this object as the \`responseBody\` field. The full callback body shape is:`,
    "",
    `\`\`\`json`,
    `{`,
    `  "state": "shipped",`,
    `  "runnerKind": "<your-runner-kind>",`,
    `  "externalRunId": "<your-session-id>",`,
    `  "stepRunId": "<the stepRunId you received in your inputs>",`,
    `  "responseBody": {`,
    `    "commitSha": "<the resulting commit SHA, or null if zero files were written>",`,
    `    "actuallyChangedFiles": ["<repo-relative path of every file actually written>"],`,
    `    "skippedFiles": ["<paths skipped, with optional reason suffix>"]`,
    `  }`,
    `}`,
    `\`\`\``,
    "",
    `${payload.instructions}`,
  ].join("\n");

  return { prompt, payloadKey };
}
